### ISSUE TITLE
구글 검색결과 페이지에서 메뉴동작 오류 (0.4.0)

### ISSUE THREAD

**Issue by b2gather** [youngminz/namuwiki#1]
- 현재버전(0.4.0)에서 구글 검색결과 페이지 메뉴중 "더보기", "검색 도구"가 오동작하고 있습니다.
- "더보기", "검색 도구"가 [뒤로가기]로 동작하는 경우도 있습니다.(동일 페이지내 연속 검색시)
- 검색어에 따라서는 괜찮은 경우도 있습니다.;;;

요근래의 사태로 인해 잘 쓰고있습니다. 감사합니다.

**Comment by youngminz** [comment]
확인해보겠습니다. 버그 리포트 감사합니다 :)

**Comment by youngminz** [comment]
버그가 확인되었습니다. 모든 링크의 onmousedown 속성을 제거해 일어났네요.
https://github.com/youngminz/namuwiki/blob/master/src/google_result.js#L135

**Comment by youngminz** [comment]
스토어에 다시 패키징하여 올렸습니다. 자동으로 업데이트된 후에는 잘 작동할 겁니다.

**Comment by b2gather** [comment]
잘쓰겠습니다~
